# VECTOR


## vector yaitu 1 baris kolom

In [2]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]

In [3]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
import numpy as np
vect_a = np.array(a)
vect_b = np.array(b)

In [5]:
vect_a + vect_b

array([ 7,  9, 11, 13, 15])

## vector Norm

In [8]:
vect_a = np.array([3, 4])
np.linalg.norm(vect_a, 1)

7.0

## Operasi penjumlahan/pengurangan/pembagian

In [9]:
#Dengan bilangan
a = [1, 2, 3]
vect_a = np.array(a)
vect_a


array([1, 2, 3])

In [10]:
vect_a / 2

array([0.5, 1. , 1.5])

In [11]:
#Antar vector
b = [10, 11, 12]
vect_b = np.array(b)
vect_b

array([10, 11, 12])

In [12]:
vect_a + vect_b

array([11, 13, 15])

## Operasi perkalian

In [13]:
#Dengan bilangan
vect_a * 2

array([2, 4, 6])

In [14]:
print(vect_a)
print(vect_b)

[1 2 3]
[10 11 12]


In [16]:
vect_a * vect_b
#vector multipitation

array([10, 22, 36])

In [17]:
#antar vector dot product 
vect_a.dot(vect_b)


68

In [18]:
np.dot(vect_a, vect_b)

68

In [19]:
vect_a@vect_b
#untuk versi terbaru

68

## Cosine Similarity

In [20]:
vect_f = np.array([4, 0])
vect_g = np.array([6, 0])

In [26]:
cos_theta = (vect_f.dot(vect_g))/ (np.linalg.norm(vect_f) * np.linalg.norm(vect_g))
cos_theta

1.0

In [27]:
rad = np.arccos(cos_theta)
rad

0.0

In [28]:
degree = np.degrees(rad)
degree

0.0

# studi kasus

In [36]:
teks_1 = 'saya pergi ke rumah nenek saya'
teks_2 = 'saya pergi ke rumah kakek saya'


In [37]:
teks_1 = [2, 1, 1, 1, 1, 0]
teks_2 = [2, 1, 1, 1, 0, 1]

vect_t1 = np.array(teks_1)
vect_t2 = np.array(teks_2)

In [38]:
cos_theta = (vect_t1.dot(vect_t2)) / (np.linalg.norm(vect_t1) * np.linalg.norm(vect_t2))
cos_theta

0.8749999999999998