# Matriks

In [1]:
import numpy as np

In [2]:
data_1 = [1,2,3]
data_2 = [[1,2,3], [4,5]]
data_3 = [[1,2,3], [4,5,6]]

In [3]:
vec = np.array(data_1)
vec

array([1, 2, 3])

In [4]:
data = np.array(data_2)
data # akan eror karena beda data

C:\Users\riyan\AppData\Local\Temp\ipykernel_27192\2384704064.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  data = np.array(data_2)


array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [5]:
mat = np.array(data_3)
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#definisi matriks
data = [[1,2], [3,4], [5,6], [7,8]] #pastikan jumlah elemen dilist sama
data_mat = np.array(data)
data_mat

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
# operasi penjumlahan dan pengurangan matriks
mat_1 = ([[1,2,3],
        [4,5,6],
        [7,8,9]])
mat_1 = np.array(mat_1)
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
mat_2 = ([[4,5,6], 
        [9,8,7], 
        [3,2,1]])
mat_2 = np.array(mat_2)
mat_2

array([[4, 5, 6],
       [9, 8, 7],
       [3, 2, 1]])

In [13]:
mat_1 + mat_2

array([[ 5,  7,  9],
       [13, 13, 13],
       [10, 10, 10]])

In [15]:
mat_1 - mat_2

array([[-3, -3, -3],
       [-5, -3, -1],
       [ 4,  6,  8]])

In [16]:
# perkalian dengan skalar
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
3*mat_1

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [19]:
mat_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
mat_2

array([[4, 5, 6],
       [9, 8, 7],
       [3, 2, 1]])

In [21]:
# perkalian dengan hadamard (element wise) 
# ini bukan perkalian matrix dengan aljabar linear
mat_1 * mat_2

array([[ 4, 10, 18],
       [36, 40, 42],
       [21, 16,  9]])

In [22]:
#live code menggunakan perkalian dengan matrix tertentu

In [24]:
mat_1@mat_2 #matrix to matrix multipitation

array([[ 31,  27,  23],
       [ 79,  72,  65],
       [127, 117, 107]])

In [25]:
np.dot(mat_1, mat_2)

array([[ 31,  27,  23],
       [ 79,  72,  65],
       [127, 117, 107]])

In [31]:
A = [[1,2],
    [3,4],
    [5,6]]
A = np.array(A)

B = [[5,6,7],
    [8,9,3]]
B = np.array(B)

In [32]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
B

array([[5, 6, 7],
       [8, 9, 3]])

In [34]:
np.dot(A, B)

array([[21, 24, 13],
       [47, 54, 33],
       [73, 84, 53]])

In [35]:
A@B

array([[21, 24, 13],
       [47, 54, 33],
       [73, 84, 53]])

In [38]:
# matrix division/pembagian tidak ada di aljabar linear masuk kedalam hadamard division


In [39]:
# Tranpose (mengubah kolom)
C = [[1,2], [3,4], [5,6]]
C = np.array(C)
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
C.T

array([[1, 3, 5],
       [2, 4, 6]])

In [41]:
#inverse
A = [[1,2], [7,8]]
A = np.array(A)
A

array([[1, 2],
       [7, 8]])

In [42]:
from numpy.linalg import inv
inv_A = inv(A)
inv_A

array([[-1.33333333,  0.33333333],
       [ 1.16666667, -0.16666667]])

In [43]:
A @ inv_A

array([[1., 0.],
       [0., 1.]])

In [44]:
inv_A @ A

array([[1., 0.],
       [0., 1.]])

In [55]:
#Determinant
from numpy.linalg import det
B = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = det(B) 
B

0.0

In [46]:
# Tensor
A = np.array([[1,2], [7,8]])
B = np.array([[1,1], [1,1]])

In [47]:
A

array([[1, 2],
       [7, 8]])

In [48]:
A.shape

(2, 2)

In [49]:
tensor = [A, B]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [7, 8]],

       [[1, 1],
        [1, 1]]])

In [50]:
tensor.shape

(2, 2, 2)

In [51]:
A = np.array([[1,2], [7,8], [1,1], [1,1]])
B = np.array([[1,1], [1,1], [1,1], [1,1]])
C = np.array([[1,1], [1,1], [1,1], [1,1]])

In [52]:
tensor = [A, B, C]
tensor = np.array(tensor)
tensor

array([[[1, 2],
        [7, 8],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [53]:
tensor.shape

(3, 4, 2)