# LinearAlgebra

## Vector dengan python

In [1]:
a = [17, 22, 99]

## Operasi penjumlahan dan pengurangan

In [2]:
a = [17, 22, 99]
b = [10, 22, 19]
c = [5, 12, 9]

In [4]:
# A+B 
import numpy as np
vect_a = np.array(a)
vect_b = np.array(b)

In [5]:
vect_a + vect_b

array([ 27,  44, 118])

In [6]:
# B-C
vect_c = np.array(c)

In [7]:
vect_b - vect_c

array([ 5, 10, 10])

## Operasi perkalian

In [8]:
# A dot C
vect_a.dot(vect_b)

2535

In [9]:
vect_a * vect_b

array([ 170,  484, 1881])

## Norm

In [13]:
v_norm= np.linalg.norm(vect_a) 
print(v_norm)

102.82995672468213


## Sudut antara vektor A dan B

In [14]:
list_a = [17, 22, 19]
list_b = [10, 20, 11]

vect_ta = np.array(list_a)
vect_tb = np.array(list_b)

In [15]:
cos_theta = (vect_ta.dot(vect_tb)) / (np.linalg.norm(vect_ta) * np.linalg.norm(vect_tb))
cos_theta

0.9759590023331435