# Non Grade Challenge 4

## Vector dengan python

In [1]:
a = [17, 22, 99]

## Operasi penjumlahan dan pengurangan

In [2]:
a = [17, 22, 99]
b = [10, 22, 19]
c = [5, 12, 9]

In [4]:
# A+B 
import numpy as np
vect_a = np.array(a)
vect_b = np.array(b)

In [5]:
vect_a + vect_b

array([ 27,  44, 118])

In [6]:
# B-C
vect_c = np.array(c)

In [7]:
vect_b - vect_c

array([ 5, 10, 10])

## Operasi perkalian

In [8]:
# A dot C
vect_a.dot(vect_b)

2535

In [9]:
vect_a * vect_b

array([ 170,  484, 1881])

## Norm

In [13]:
v_norm= np.linalg.norm(vect_a) 
print(v_norm)

102.82995672468213


## Sudut antara vektor A dan B

In [14]:
list_a = [17, 22, 19]
list_b = [10, 20, 11]

vect_ta = np.array(list_a)
vect_tb = np.array(list_b)

In [15]:
cos_theta = (vect_ta.dot(vect_tb)) / (np.linalg.norm(vect_ta) * np.linalg.norm(vect_tb))
cos_theta

0.9759590023331435

# Non Graded Challenge 5

### 1. Tensor dibawah ini dengan Python

In [2]:
import numpy as np

In [8]:
A = np.array([[23,50], [7,12], [75,21], [57,12]])
B = np.array([[57,67], [99,43], [87,26], [18,84]])

In [9]:
tensor = [A, B]
tensor = np.array(tensor)
tensor

array([[[23, 50],
        [ 7, 12],
        [75, 21],
        [57, 12]],

       [[57, 67],
        [99, 43],
        [87, 26],
        [18, 84]]])

## 2. Perkalian matrix

In [10]:
A = [[23,50,19],
    [7,12,109],
    [57,67,98]]
A = np.array(A)

B = [17,22,19]
B = np.array(B)

In [11]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [12]:
B

array([17, 22, 19])

In [13]:
A@B

array([1852, 2454, 4305])